# Generated by Django 3.0.8 on 2020-07-23 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postphotos',
            name='photo_id',
        ),
        migrations.RemoveField(
            model_name='postphotos',
            name='post_id',
        ),
        migrations.RemoveField(
            model_name='userphotos',
            name='photo_id',
        ),
        migrations.RemoveField(
            model_name='userphotos',
            name='user_id',
        ),
        migrations.AddField(
            model_name='photo',
            name='comment_photos',
            field=models.ManyToManyField(to='wallApp.Comment'),
        ),
        migrations.AddField(
            model_name='photo',
            name='post_photos',
            field=models.ManyToManyField(to='wallApp.Post'),
        ),
        migrations.AddField(
            model_name='photo',
            name='user_photos',
            field=models.ManyToManyField(to='wallApp.User'),
        ),
        migrations.DeleteModel(
            name='commentPhotos',
        ),
        migrations.DeleteModel(
            name='postPhotos',
        ),
        migrations.DeleteModel(
            name='userPhotos',
        ),
    ]
