# Generated by Django 3.0.8 on 2020-07-23 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0002_auto_20200723_0639'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='comment_photos',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='post_photos',
            new_name='post',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='privacity_id',
            new_name='privacity',
        ),
        migrations.RenameField(
            model_name='photo',
            old_name='user_photos',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='user_id',
            new_name='user',
        ),
    ]
