# Generated by Django 3.0.8 on 2020-08-03 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0002_auto_20200803_0916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='likes',
            new_name='comment_likes',
        ),
    ]
