# Generated by Django 3.0.8 on 2020-07-26 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0005_auto_20200725_2206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='deleted_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(null=True),
        ),
    ]
