# Generated by Django 3.0.8 on 2020-08-05 00:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0005_auto_20200803_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='photo',
            name='post',
            field=models.ManyToManyField(related_name='photos', to='wallApp.Post'),
        ),
        migrations.AlterField(
            model_name='photo',
            name='user',
            field=models.ManyToManyField(related_name='photo_owner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='post',
            name='privacity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacity', to='wallApp.Privacity'),
        ),
        migrations.AlterField(
            model_name='post',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
