# Generated by Django 3.0.8 on 2020-07-26 03:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallApp', '0006_auto_20200725_2209'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='privacity_id',
            new_name='privacity',
        ),
    ]
